spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:file:/Users/Daniel/Downloads/springboot-journal/src/main/java/daniel/kubik/lab04/data/journal
